# generated by datamodel-codegen:
#   filename:  test.story-in-sequence.json
#   timestamp: 2026-09-15T22:42:50+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class Image(BaseModel):
    datetaken: str
    license: str
    title: str
    text: str
    album_id: str
    longitude: str
    url_o: Optional[str] = None
    secret: str
    media: str
    latitude: str
    id: str
    tags: str
    farm: Optional[str] = None
    server: Optional[str] = None
    url_m: Optional[str] = None


class Album(BaseModel):
    description: str
    title: str
    farm: str
    date_update: str
    primary: str
    server: str
    date_create: str
    photos: str
    secret: str
    owner: str
    vist_label: str
    id: str


class Annotation(BaseModel):
    original_text: str
    album_id: str
    photo_flickr_id: str
    setting: str
    worker_id: str
    story_id: str
    tier: str
    worker_arranged_photo_order: int
    text: str
    storylet_id: str


class DataModel(BaseModel):
    images: List[Image]
    info: str
    albums: List[Album]
    type: str
    annotations: List[List[Annotation]]
